// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLir354zTZralJdjBGgGQcSA6lYPOoGik',
    appId: '1:768668830005:web:62a4aba71f3a466878647c',
    messagingSenderId: '768668830005',
    projectId: 'labaduh-22858',
    authDomain: 'labaduh-22858.firebaseapp.com',
    storageBucket: 'labaduh-22858.firebasestorage.app',
    measurementId: 'G-Z5CZ1N9VHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2mFntgKTzi9wxGpiqAwrR_7tmBEgW9Q',
    appId: '1:768668830005:android:1600ae35bdc94fc878647c',
    messagingSenderId: '768668830005',
    projectId: 'labaduh-22858',
    storageBucket: 'labaduh-22858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmVk_kha93scj6_0NV31V6zoqnSiKZzIc',
    appId: '1:768668830005:ios:86db6d80539e5b3f78647c',
    messagingSenderId: '768668830005',
    projectId: 'labaduh-22858',
    storageBucket: 'labaduh-22858.firebasestorage.app',
    iosBundleId: 'com.example.labaduh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmVk_kha93scj6_0NV31V6zoqnSiKZzIc',
    appId: '1:768668830005:ios:86db6d80539e5b3f78647c',
    messagingSenderId: '768668830005',
    projectId: 'labaduh-22858',
    storageBucket: 'labaduh-22858.firebasestorage.app',
    iosBundleId: 'com.example.labaduh',
  );
}
